version: '3.8'

# =============================================================================
# CRYPTO AUDIT SYSTEM - COMPLETE DOCKER COMPOSE
# =============================================================================
# Cross-platform (Windows, macOS, Linux)
# All agents are containerized with real crypto configurations
# One command to rule them all: docker-compose up
# =============================================================================

services:
  # ---------------------------------------------------------------------------
  # CENTRAL API SERVER
  # ---------------------------------------------------------------------------
  system-scan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: system-scan
    ports:
      - "9000:9000"
    volumes:
      - server-data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - crypto-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/api/v1/admin/stats"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ---------------------------------------------------------------------------
  # LINUX AGENT #1 - MODERN CONFIGURATION
  # ---------------------------------------------------------------------------
  # Profile: Ubuntu 22.04 + OpenSSL 3.0 + Modern ciphers
  linux-agent-modern:
    build:
      context: ./agents/linux
      dockerfile: Dockerfile.modern
      args:
        API_SERVER: http://system-scan:9000
    container_name: linux-agent-modern
    hostname: ubuntu-modern-agent
    depends_on:
      - system-scan
    environment:
      - AGENT_PROFILE=modern
      - API_BASE_URL=http://system-scan:9000
      - POLL_INTERVAL=10
      - AGENT_NAME=ubuntu-modern-agent
    networks:
      - crypto-network
    restart: unless-stopped
    privileged: false
    cap_add:
      - SYS_ADMIN  # For systemd operations
    volumes:
      - agent-modern-data:/var/lib/crypto_agent

  # ---------------------------------------------------------------------------
  # LINUX AGENT #2 - LEGACY CONFIGURATION
  # ---------------------------------------------------------------------------
  # Profile: Debian 10 + OpenSSL 1.1 + Legacy ciphers + Weak protocols
  linux-agent-legacy:
    build:
      context: ./agents/linux
      dockerfile: Dockerfile.legacy
      args:
        API_SERVER: http://system-scan:9000
    container_name: linux-agent-legacy
    hostname: debian-legacy-agent
    depends_on:
      - system-scan
    environment:
      - AGENT_PROFILE=legacy
      - API_BASE_URL=http://system-scan:9000
      - POLL_INTERVAL=10
      - AGENT_NAME=debian-legacy-agent
    networks:
      - crypto-network
    restart: unless-stopped
    privileged: false
    cap_add:
      - SYS_ADMIN
    volumes:
      - agent-legacy-data:/var/lib/crypto_agent

  # ---------------------------------------------------------------------------
  # LINUX AGENT #3 - MIXED CONFIGURATION
  # ---------------------------------------------------------------------------
  # Profile: Alpine Linux + OpenSSL 1.1.1 + Mixed modern/legacy settings
  linux-agent-mixed:
    build:
      context: ./agents/linux
      dockerfile: Dockerfile.mixed
      args:
        API_SERVER: http://system-scan:9000
    container_name: linux-agent-mixed
    hostname: alpine-mixed-agent
    depends_on:
      - system-scan
    environment:
      - AGENT_PROFILE=mixed
      - API_BASE_URL=http://system-scan:9000
      - POLL_INTERVAL=10
      - AGENT_NAME=alpine-mixed-agent
    networks:
      - crypto-network
    restart: unless-stopped
    privileged: false
    cap_add:
      - SYS_ADMIN
    volumes:
      - agent-mixed-data:/var/lib/crypto_agent

# =============================================================================
# NETWORKS
# =============================================================================
networks:
  crypto-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

# =============================================================================
# VOLUMES (Persistent storage)
# =============================================================================
volumes:
  server-data:
    driver: local
  agent-modern-data:
    driver: local
  agent-legacy-data:
    driver: local
  agent-mixed-data:
    driver: local

# =============================================================================
# USAGE INSTRUCTIONS
# =============================================================================
# 
# Start everything:
#   docker-compose up -d
#
# View logs:
#   docker-compose logs -f
#   docker-compose logs system-scan
#   docker-compose logs linux-agent-modern
#
# Stop everything:
#   docker-compose down
#
# Reset (clean start):
#   docker-compose down -v
#   docker-compose up -d --build
#
# Access Dashboard:
#   http://localhost:9000
#
# Trigger scans:
#   Open dashboard → Admin Dashboard → Click "Trigger Scan" next to any agent
#
# =============================================================================