version: '3.8'

services:
  repo_scanner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crypto_scanner_backend
    ports:
      - "8002:8001"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://scanuser:scanpass@db:5432/repo_scanner_db
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: postgres:14-alpine
    container_name: crypto_scanner_db
    environment:
      - POSTGRES_USER=scanuser
      - POSTGRES_PASSWORD=scanpass
      - POSTGRES_DB=repo_scanner_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scanuser -d repo_scanner_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  postgres_data: